version: "3"

volumes:
  cosmogony_pgdata:

services:
  cosmogony_postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
      - cosmogony_pgdata:/var/lib/postgresql/data
    env_file: .cosmogony_env

  importer:
    image: osmwithoutborders/cosmogony-importer
    env_file: .cosmogony_env
    volumes:
      - ${PATH_TO_COSMOGONY_DIR:-./cosmogony_data}:/data
    links:
      - cosmogony_postgres:postgres
